version: "3.8"
services:
  db:
    image: 'mysql:5.7'
    container_name: db
    command: '--init-file /data/application/init.sql'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: instruments
    volumes:
      - './dbfile:/var/lib/mysql'
      - './init.sql:/data/application/init.sql'
    ports:
      - '3308:3306'
    restart: 'always'
  php-apache-server:
    image: 'ganitev:latest'
    container_name: php-apache
    ports:
      - '8090:80'
    volumes:
      - './php:/var/www/html'
    depends_on:
      - db

volumes:
  www:
  dbData:

