apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  DB_USERNAME: U2V2YTE5NzM= # зашифр base 64 Seva1973 (echo -n "Seva1973" | base64)
  DB_PASSWORD: cXc5OTk5eng= # зашифр base 64 qw9999zx (echo -n "qw9999zx" | base64)
