
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "vagrXenial64"
  # your network. похоже на то, если я раздокументировал эту строк и не обозначил другого, система должна поддерживать и "NAT" НА "BRIGE"
  # Но выбор бридж (2)не дал результата поэтому после выхова ifconfig, я выбрал бридж : т.е IP адресу который соотв. бриджу - 10.0.0.6
  config.vm.network "public_network"
  # Run Ansible from the Vagrant Host
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end


