CREATE DATABASE IF NOT EXISTS reg1;
CREATE USER IF NOT EXISTS 'user'@'%' 
IDENTIFIED BY 'password';
GRANT SELECT,UPDATE,INSERT ON reg1.* TO 'user'@'%';
FLUSH PRIVILEGES;
USE reg1;
CREATE TABLE IF NOT EXISTS regions (
  region VARCHAR(100) NOT NULL,
  maincity VARCHAR(50) NOT NULL,
  population INT (10) NOT NULL);

