apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  DB_USERNAME: cm9vdA== # зашифр base 64 root (echo -n "Seva1973" | base64)
  DB_PASSWORD: cXc5OTk5eng= # зашифр base 64 qw9999zx (echo -n "qw9999zx" | base64)
